### PR TITLE
gocty type alias support

### PR DESCRIPTION
**Pull request by paultyng**
Each commit is discrete, happy to open multiple PRs if you prefer (or just close this if you aren't interested).

### CODE REVIEW

**Comment by paultyng** [comment]
The `Change` interface change (and related struct changes) are breaking, so care necessary there probably.

**Comment by apparentlymart** [comment]
This `diff` package is, to be honest, kinda abandoned at this point. I eventually concluded it better to just retain full old/new values and produce a _visual_ diff for humans when needed, as Terraform does.

I'm okay with making changes to it if you see a useful reason for it, and wouldn't worry at all about backward compatibility in `cty/diff` in particular (there should be no callers of it because it doesn't actually _work_) but on the other hand maybe there's enough stuff in this codebase already that this would be better off split out into its own repository and maintained separately, so that `cty` can get a v1.0.0 release without this experimental functionality in it.

**Comment by paultyng** [comment]
@apparentlymart just found a minor bug in `gocty`, I can split it out to a new PR, basically issues handling alias types (JSON does, so I looked at its implementation). I've only tested strings, now looking at other primitives.

**Comment by paultyng** [comment]
I'm fine with losing the diff functionality, the `Path` helpers may be useful to others though to start paths (for example, in error messages).

**Pull request merged**
